const $=id=>document.getElementById(id);const q=$('q'),results=$('results'),detail=$('detail');
const norm=s=>(s??'').toString().toUpperCase().replace(/[^A-Z0-9\u0980-\u09FF]+/g,'');
const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let current=null,active=-1,currentMatches=[];$('metaCount').textContent=`${window.INVENTORY_DATA.length} products`;
function stockClass(v){const n=Number(v);if(Number.isNaN(n))return'good';if(n===0)return'zero';if(n<=10)return'low';return'good'}
function render(){const term=norm(q.value.trim());active=-1;if(!term){results.style.display='none';detail.style.display='none';currentMatches=[];return}currentMatches=window.INVENTORY_DATA.filter(x=>norm(`${x.name} ${x.code} ${x.category}`).includes(term)).slice(0,100);results.innerHTML='';if(!currentMatches.length){results.innerHTML='<div class="empty">কোনো matching product পাওয়া যায়নি</div>'}else currentMatches.forEach((x,i)=>{const el=document.createElement('div');el.className='result';el.innerHTML=`<div><div class="r-name">${esc(x.name||'-')}</div><div class="r-meta">${esc(x.category||'')}</div></div><div class="r-code">${esc(x.code||'No code')}</div>`;el.onclick=()=>show(x);results.appendChild(el)});results.style.display='block'}
function show(x){current=x;$('dName').textContent=x.name||'-';$('dCode').textContent=x.code||'-';$('dCategory').textContent=x.category||'-';$('dSize').textContent=x.size||'-';$('dUnit').textContent=x.unit||'-';$('dStock').textContent=(x.stock===''||x.stock==null)?'Not updated':x.stock;$('dStock').className=`value stock ${stockClass(x.stock)}`;$('dPrice').textContent=(x.price===''||x.price==null)?'-':x.price;$('dRemarks').textContent=x.remarks||'-';$('dLocation').textContent=x.location||'Hamayetpur Warehouse';detail.style.display='block';results.style.display='none';q.value=x.code||x.name}
function move(step){const els=[...document.querySelectorAll('.result')];if(!els.length)return;active=Math.max(0,Math.min(els.length-1,active+step));els.forEach((el,i)=>el.classList.toggle('active',i===active));els[active].scrollIntoView({block:'nearest'})}
q.addEventListener('input',render);q.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();move(1)}if(e.key==='ArrowUp'){e.preventDefault();move(-1)}if(e.key==='Enter'&&active>=0){e.preventDefault();show(currentMatches[active])}if(e.key==='Escape')clearAll()});
$('clearBtn').onclick=clearAll;function clearAll(){q.value='';results.style.display='none';detail.style.display='none';current=null;q.focus()}
$('copyBtn').onclick=async()=>{if(!current)return;const text=`${current.name}\nCode: ${current.code||'-'}\nCategory: ${current.category||'-'}\nSize: ${current.size||'-'}\nUnit: ${current.unit||'-'}\nStock: ${current.stock||0}\nLocation: ${current.location||'Hamayetpur Warehouse'}`;await navigator.clipboard.writeText(text);$('copyBtn').textContent='Copied';setTimeout(()=>$('copyBtn').textContent='Copy',1200)};
//if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
